# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2 
    displayName: ".NET Core 3.1.x"
    inputs:
      version: '3.1.x'
      packageType: sdk
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  # - script: dotnet test '$(System.DefaultWorkingDirectory)/test/SimpleAPI.Test/SimpleAPI.Test.csproj' --configuration $(buildConfiguration) --logger trx --results-directory '$(System.DefaultWorkingDirectory)/TestResult' 
  #   displayName: 'dotnet build $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: "Test"
    inputs:
      command: test
      projects: '$(System.DefaultWorkingDirectory)/test/SimpleAPI.Test/SimpleAPI.Test.csproj'
      arguments: '--configuration $(buildConfiguration)' 
        
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
    
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SimpleAPI/SimpleAPI.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: 'publish artifacts'
